# Generated by Django 2.0.1 on 2018-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytaxiapp', '0004_auto_20180131_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('accepted_by_driver', 'accepted_by_driver'), ('driver_came', 'driver_came'), ('customer_in_the_car', 'customer_in_the_car'), ('completed', 'completed')], default='new', max_length=127),
        ),
    ]
